# Generated by Django 3.0.6 on 2020-06-02 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('equipment_name', models.CharField(max_length=50)),
                ('purpose', models.TextField()),
                ('speciality', models.CharField(max_length=25)),
                ('picture', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='General_Specs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.CharField(blank=True, max_length=300, unique=True)),
                ('content', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Technical_Specs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Technical_Report',
            fields=[
                ('report_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('modification_date', models.DateField()),
                ('addition_date', models.DateField()),
                ('technology_level', models.CharField(max_length=10)),
                ('facility_level', models.CharField(max_length=10)),
                ('equipment_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='techspecs.Equipment')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='gspecs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='techspecs.General_Specs'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='tspecs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='techspecs.Technical_Specs'),
        ),
    ]
