# Generated by Django 3.0.6 on 2020-08-12 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='General_Specs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Technical_Specs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Technical_Report_Copy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('version', models.PositiveIntegerField()),
                ('equipment_name', models.CharField(max_length=50)),
                ('purpose', models.TextField(default='654')),
                ('speciality', models.CharField(max_length=25)),
                ('picture', models.ImageField(max_length=1000, upload_to='media/')),
                ('modification_date', models.CharField(max_length=20)),
                ('addition_date', models.CharField(max_length=20)),
                ('technology_level', models.CharField(max_length=10)),
                ('facility_level', models.CharField(max_length=10)),
                ('general_specs', models.ManyToManyField(blank=True, to='techspecs.General_Specs')),
                ('technical_specs', models.ManyToManyField(blank=True, to='techspecs.Technical_Specs')),
            ],
        ),
        migrations.CreateModel(
            name='Technical_Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('version', models.PositiveIntegerField()),
                ('equipment_name', models.CharField(max_length=50)),
                ('purpose', models.TextField(default='654')),
                ('speciality', models.CharField(max_length=25)),
                ('picture', models.ImageField(max_length=1000, upload_to='media/')),
                ('modification_date', models.CharField(max_length=20)),
                ('addition_date', models.CharField(max_length=20)),
                ('technology_level', models.CharField(max_length=10)),
                ('facility_level', models.CharField(max_length=10)),
                ('general_specs', models.ManyToManyField(blank=True, to='techspecs.General_Specs')),
                ('technical_specs', models.ManyToManyField(blank=True, to='techspecs.Technical_Specs')),
            ],
        ),
    ]
