# Generated by Django 3.0.6 on 2020-06-02 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('techspecs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='gspecs',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='tspecs',
        ),
        migrations.AddField(
            model_name='general_specs',
            name='equipment_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='techspecs.Equipment'),
        ),
        migrations.AddField(
            model_name='technical_specs',
            name='equipment_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='techspecs.Equipment'),
        ),
    ]
