# Generated by Django 3.0.6 on 2020-08-12 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techspecs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general_specs',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='general_specs',
            name='value',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='technical_specs',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='technical_specs',
            name='value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
