# Generated by Django 3.0.6 on 2020-06-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techspecs', '0003_auto_20200602_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='features',
        ),
        migrations.RemoveField(
            model_name='general_specs',
            name='equipment_name',
        ),
        migrations.RemoveField(
            model_name='technical_specs',
            name='equipment_name',
        ),
        migrations.AddField(
            model_name='equipment',
            name='general_specs',
            field=models.ManyToManyField(to='techspecs.General_Specs'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='technical_specs',
            field=models.ManyToManyField(to='techspecs.Technical_Specs'),
        ),
    ]
