# Generated by Django 3.0.6 on 2020-06-02 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techspecs', '0004_auto_20200602_2134'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
