# Generated by Django 3.0.6 on 2020-06-04 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techspecs', '0005_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='general_specs',
            field=models.ManyToManyField(blank=True, to='techspecs.General_Specs'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='technical_specs',
            field=models.ManyToManyField(blank=True, to='techspecs.Technical_Specs'),
        ),
    ]
