# Generated by Django 3.0.6 on 2020-06-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techspecs', '0006_auto_20200604_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='picture',
            field=models.ImageField(default='val10', max_length=1000, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='technical_report',
            name='report_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
