# Generated by Django 3.0.6 on 2020-06-09 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techspecs', '0008_auto_20200609_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technical_report',
            name='report_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
