# Generated by Django 3.0.6 on 2020-06-09 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techspecs', '0009_auto_20200609_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technical_report',
            name='report_id',
            field=models.CharField(default=0, max_length=30, primary_key=True, serialize=False),
        ),
    ]
